include $(CLEAR_VARS)
LOCAL_MODULE    := MIX
LOCAL_CFLAGS	:= -Werror
LOCAL_C_INCLUDES:= $(LOCAL_PATH)/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/genlib
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/rtcmix
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/conf
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/audio
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/sndlib
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/include
LOCAL_STATIC_LIBRARIES := gen
LOCAL_SRC_FILES := insts/base/MIX/MIX.cpp
include $(BUILD_SHARED_LIBRARY)
